name: Build-Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository.
      - uses: actions/checkout@v2

      # Set up Python.
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      # Set up Node.
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      # Install Python dependencies and build Sphinx docs.
      - name: Build Sphinx Documentation
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          cd docs
          make html
          cd ..

      # Install JS dependencies and build JSDoc docs.
      - name: Build JSDoc Documentation
        run: |
          npm install
          npx jsdoc -c jsdoc.conf.json

      # Deploy both docs (_build/html and jsdoc) to GitHub Pages.
      - name: Deploy Documentation to GitHub Pages
        run: |
          # Ensure that both Sphinx and JSDoc docs are inside the "docs" folder.
          # This command pushes everything inside "docs/" to the gh-pages branch.
          ghp-import -n -p -f docs
