name: Build-Docs

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: Build Sphinx Documentation
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          cd docs
          make html
          cd ..

      - name: Build JSDoc Documentation
        run: |
          npm install
          npx jsdoc -c jsdoc.conf.json

      # New step: Combine Sphinx and JSDoc outputs
      - name: Merge Documentation Outputs
        run: |
          # Ensure the target directory exists in the Sphinx build output
          mkdir -p docs/_build/html/jsdoc
          # Copy all files from the JSDoc output folder into the Sphinx build folder
          cp -R docs/jsdoc/* docs/_build/html/jsdoc/

      - name: Deploy Documentation to GitHub Pages
        run: |
          ghp-import -n -p -f docs/_build/html
